# Generated by Django 3.0.6 on 2020-05-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomrate',
            name='roomRate',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
